### ISSUE TITLE
Unable to use the configured VUs in different threadGroups while using Jmeter Scripts

### ISSUE THREAD

**Issue by srivastavsaurabh59** [aws-solutions/distributed-load-testing-on-aws#122]
**Describe the bug**
While using AWS DLT, all thread groups runs with same number of VUs. Although different thread groups are set with different VUs in Jmeter script

**To Reproduce**
1. Create 2 different threadGroups in a Testplan in Jmeter.
2. Set the Test plan as "Run Thread groups consecutively"(i.e., one at a time) option.
3. Set the ThreadGroup-1: 1VUs and ThreadGroup-2 as 4 VUs.
4. Add the API requests in thread groups and then to the Script in AWS DLT (Distributed Load testing).
5. Set the Instance=1, Concurrency=1, Rampup=1min and Hold=9 mins to run complete test for 10mins.

**Expected behavior**
1. ThreadGroup-1 is expected to run only once and then threadGroup-2 is expected to run for the 4VUs for next remaining time period.

- [ ] Jmeter Version: apache-jmeter-5.4.3
- [ ] AWS DLT Region: me-south-1 (bahrain)

Issue:(Actual result):
1. Both the ThreadGroup-1 and ThreadGroup-2 runs parallely.
2. Although the threadGroup-1 is configured for 1 VU for 1 API request, it gets executed multiple times.
3. ThreadGroup-2 as 4 VUs, overridden by 1 VU defined in UI of DLT.

Questions and Issues while using Jmeter in AWS DLT(Distributed Load testing):
- How can we use such test plan in AWS DLT, when we want to configure different virtual Users(VUs) on different thread Groups?
- The throughput displayed on AWS DLT result is incorrect when compared with result file in Jmeter. 
- While doing live monitoring during the test run, there is no option to see the individual APIs running under the Real Time Metrics section. User should be able to see the the APIs by filtering of their choice.
- If I schedule a test for 1 hr it takes almost 2+ hours to complete the test in AWS DLT.
- Result csv file should be automatically generated in S3 bucket where log file are generated for debugging purposes.
- While using Jmeter scripts, the Concurrency, RampUp,Hold should be made optional, so that all the configurations are taken from the Jmeter script. Any information when this will be implemented, as we want to use this tool in our project in middle east region.

**Comment by G-Lenz** [comment]
The backend of the solution uses the Taurus testing framework, which runs JMeter. The way Taurus works with a JMeter script using multiple thread groups is that when both concurrency is defined in the taurus script (created by the solution with input from the UI) and VUs (defined in your script) are defined the one in the yaml(UI defined concurrency) will be divided in proportion to the concurrency (VU) values in thread groups. You can read more in the [Jmeter documentation](https://gettaurus.org/docs/JMeter/#Run-Existing-JMX-File). So in your case you are dividing 1 concurrency at a ratio of 1:4, but since the minimum is 1, they are both just running 1. If you would like to run a test with 4 users in one thread group and 1 user in another, you can define the concurrency in the UI as 4. This will split it at a ratio of 4:1 into each thread group, so you'll have 4 users in one thread group and 1 in another, as desired.
