### ISSUE TITLE
Issue: Removal of Supporting Functions in Version 3.2.16 Affecting Selenium Testing in Distributed Load Testing

### ISSUE THREAD

**Issue by poojahukkeri-CF** [aws-solutions/distributed-load-testing-on-aws#195]
Dear [Project Maintainers/Team],

I am writing to raise an issue regarding the recent changes in version 1.16.29 Specifically, it appears that two supporting functions critical for Selenium testing have been removed. As a result, Selenium testing is no longer supported in distributed load testing environments.

Details:

Removed Functions: The two supporting functions essential for Selenium testing.
RUN rm -rf /root/.bzt/selenium-taurus
RUN rm -rf /root/.bzt/gatling-taurus
Version Affected: 1.16.29
Impact:

Selenium testing in distributed load testing is currently unsupported.
This removal hinders our ability to perform effective UI testing.

Questions:

1. What was the reason for removing these functions in version 1.16.29?
2. Is there any plan to reintroduce these functions in future releases?
3. What are the recommended methods for performing UI testing with the current version?
4. Where can we find the compatible driver path to run JMeter scripts with Selenium in the latest version?
5. Understanding the rationale behind these changes and the future roadmap will help us plan our testing strategy accordingly.

Thank you for your attention to this matter. We look forward to your response.

Best regards,

**Comment by kamyarz-aws** [comment]
1 - Selenium is not officially supported and the Docker image and stack is customizable so users that wants the feature can add it themselves. The reason for removal, was because we didnt want to maintain and resolve issues regarding  dependencies of a feature that is not officially supported so we decided to remove it.
2 - We are discussing to fully support selenimum in the future releases but it is not confirmed yet. It is likely that we add it in the future releases. We cannot provide a date at this point.
3 - You can customize the stack to use selenium with the current stack.
4 - Even for this to add the webdriver you need to customize the stack so adding selenium back is more recommended.

Even with the installation of selenium still the stack needed to be customized for selenium scripts to be actually running on DLT, so in your case if you still want to use Selenium, all you need is to customize the dockerfile get rid of this `RUN rm -rf /root/.bzt/selenium-taurus` and build the image without it. Deploy the image in a public-ecr repository and deploy your customized stack with that image. This way the dependencies of the selenium is back and then you can develop on top of our stack to support selenium.
