### ISSUE TITLE
How to split CSV input file amongst all containers/tasks?

### ISSUE THREAD

**Issue by jayczech23** [aws-solutions/distributed-load-testing-on-aws#35]
I am trying to use a large single input CSV file split amonst all of the containers / tasks I am executing load tests on. It appears that each container is using the same users (rows 1 - 100 for example) for each container, which results in only the first 100 users being used for authentication step in JMeter test, even if trying to test 1000 concurrent users.

How do you solve for this? If I have a large CSV input file and I want to split it between each container so that each has a set of unique users to use for testing?

**Comment by beomseoklee** [comment]
@jayczech23 Thanks for your feedback.

Unfortunately, we only support what JMeter script itself is doing, so I believe once Fargate containers are running, they only go through what JMeter script says. But I'll look for a solution if splitting a large file in pieces to each Fargate tasks is possible.

**Comment by jayczech23** [comment]
@beomseoklee 

Thank you very much for your prompt reply!

I was thinking of breaking the single large input file into multiple ones and distribute that amongst the tasks somehow. 
Thank you for looking into this, please let me know if need any additional information for use case.

Will keep this thread updated with any findings on a potential workaround solution for this use case.

**Comment by madhu-gudivaka** [comment]
Request made in https://github.com/awslabs/distributed-load-testing-on-aws/issues/54 if accommodated in the solution would eliminate this need as well.

**Comment by tpark-itops** [comment]
Any update to this?

**Comment by tpark-itops** [comment]
I found following pages on BlazeMeter:
- https://guide.blazemeter.com/hc/en-us/articles/206733699-How-to-setup-a-different-CSV-file-for-each-JMeter-engine-
- https://guide.blazemeter.com/hc/en-us/articles/207420585-CSV-File-Upload (How to set up a different CSV file for each JMeter engine)
Would {__P(InstanceID)} or ${__env(TAURUS_SESSIONS_INDEX)} works on DLT? If not, is there a property in DLT that identifies instance ID?

**Comment by serdarbuyuran** [comment]
Any update to this?
I've tried. {__P(InstanceID)} or ${__env(TAURUS_SESSIONS_INDEX)} does not work on DLT.
is there a property in DLT that identifies instance ID?

**Comment by tpark-itops** [comment]
Yes, this didn't work for me either. To make it work, I had to manually tweak TaskRunner lambda function and pass in InstanceID as the environment variable. Here's the feature enhancement request that I submitted - https://github.com/aws-solutions/distributed-load-testing-on-aws/issues/101

**Comment by serdarbuyuran** [comment]
Thanks tpark-itops

Hi beomseoklee, In jmeter performance tests, each computer should have a different parameter file(.csv) to use. Otherwise, if the same parameter file is sent to all computers, all computers will run the test with the same parameters.This is undesirable for many performance testing scenarios. Like other cloud performance testing solutions, you can create a solution for this.

Thank you for your support.

**Comment by G-Lenz** [comment]
Hi,

#54 has been since accommodated, hopefully this provides a workaround.

We have also added the environment variable mentioned in #101 to our backlog in order to allow for multiple JMeter engines.

Another potential workaround is supply a different CSV dataset to different thread groups in JMeter. This does not have each container running a different set of parameters, but you will have multiple scenarios running, they will just be running on the same container. For example if you specified a thread group using CSV X and a thread group with CSV Y, each Fargate machine will be running separate requests, one with X and one with Y.

**Comment by phillee-cqe** [comment]
> @jayczech23 Thanks for your feedback.
> 
> Unfortunately, we only support what JMeter script itself is doing, so I believe once Fargate containers are running, they only go through what JMeter script says. But I'll look for a solution if splitting a large file in pieces to each Fargate tasks is possible.

Hi @beomseoklee - I know this is an old thread but I am unable to locate any solution. Please could you kindly provide an update on this issue/ challenge. Has a solution been implemented that would split a given data file into different batches across task instances? If not, is there an accessible variable (via a JMeter Groovy script) that can identify the Task ID?


Thanks,
Phil.

**Comment by kamyarz-aws** [comment]
Hi @phillee-cqe 

Unfortunately we havent been able to prioritize this. I can look into workaround in more detail and see what I can find and get back to you. Is this any helpful https://github.com/aws-solutions/distributed-load-testing-on-aws/issues/35#issuecomment-1322420712?

**Comment by phillee-cqe** [comment]
Hi @kamyarz-aws 

Many thanks for responding.

The suggestions within [https://github.com/aws-solutions/distributed-load-testing-on-aws/issues/35#issuecomment-1322420712?] in particular that suggested by @tpark-itops doesn't provide a clear understanding of its implementation. The available task URI variables don't allow you to distinguish a particular task (for example the ARN) in order to then split the shared CSV file accordingly (using in combination the threadNum, for example).

I, and I suspect the community using DLT, would very much appreciate the proposal of a workaround or indeed an update with the feature included. This particular capability is fundamental in being to run a representative performance test. Without it the tool is significantly limited in its application and alternatives, such as BlazeMeter, would need to be used.


Regards,
Phil.
