### ISSUE TITLE
How to run the ui locally

### ISSUE THREAD

**Issue by drazengrabovac** [aws-solutions/distributed-load-testing-on-aws#87]
**Is your feature request related to a problem? Please describe.**
We are considering using and customising this really nice project. 
I tried to run the ui locally and I get a blank screen. This is what I tried in the `source/console` folder: `npm run start`
I also try to first build it and then run ` serve -s console`, same result. 
This is what I see in the console:
![Screenshot 2022-03-22 at 09 21 34](https://user-images.githubusercontent.com/79849083/159437708-fc8de046-5430-4b00-a033-9e9345f25800.png)

Is it possible to run the ui locally?
If so, could you please add documentation on how to run it locally?

**Describe the feature you'd like**
I would like to have a short section in the documentation on how to run the project locally.

**Comment by G-Lenz** [comment]
Hi @drazengrabovac,

You can run the UI by using npm run start. In order to run it locally you will also need to include the aws_config.js file which contains the necessary information about your aws resources for the front end. This can be found in the S3 console bucket. The bucket should have a prefix of `<your-stack-name>-dltconsoleresources`. In the bucket there is an assets folder that contains the aws_config.js file. That file needs to be placed in an assets folder under `source/console/public`. Once that file is there you can run `npm run start` and it should be running locally and connected to the proper resources on the back end.

**Comment by drazengrabovac** [comment]
@G-Lenz thanks a lot for the answer. This helps us in testing out changes locally.

**Comment by G-Lenz** [comment]
No problem, I'm glad we were able to help. 
Thank you for raising the issue, we will also add an item to our backlog for improving documentation with guidance on how to run the UI locally. 
I'm going to close this issue, if you have you still have questions around running the UI locally or feel this was not properly resolved, feel free to re-open this issue.
