### ISSUE TITLE
Specify throughput (requests per second)

### ISSUE THREAD

**Issue by AboulEinein** [aws-solutions/distributed-load-testing-on-aws#88]
Is there a way to specify the throughput or number of requests per second?
I know it's not currently exposed from the UI, but is there a way to specify it from the JMeter script?

**Comment by chgar101** [comment]
Hi @AboulEinein, I don't really have an answer but we are faced with a similar challenge. Using JMeter I used the "Arrival Thread Group" and then have my requests under it and can specify a a target rate (requests/min). If I run the test through the traditional way with JMeter it appears to work as expected but when I run within the AWS distributed load testing console it appears that the numbers of requests don't add up in the results that are given. Makes me think also if AWS honors the parameters set in JMeter for ramp-up, hold time, and target rate. This could be because of the bug documented by @zxkane #103. I wanted to see if anyone else had any experiences with this.

**Comment by G-Lenz** [comment]
We have added to our backlog to include the Taurus throughput variable into the UI which would allow to put a max limit on RPS.

In the meantime you can add the constant throughput timer to your JMeter scripts in order to try and and achieve a certain amount of RPS. This timer can not speed up requests (they are dependent on how fast your machine responds). However it can slow down requests so that you are not exceeding a specific throughput. You can see the documentation here: https://www.blazemeter.com/blog/jmeter-throughput
